EBandPlannerROS:
  costmap_weight: 10.569401148308533
  eband_external_force_gain: 2.593130584808948
  eband_internal_force_gain: 2.640917238455838
  eband_min_relative_overlap: 0.7157573149664761
  k_damp: 5.037451363768019
  k_prop: 7.569186374063609
  max_rotational_acceleration: 2.9
  max_translational_acceleration: 1.3
  max_vel_lin: 1.6
  max_vel_th: 2.6
  rotation_correction_threshold: 0.7094628320732485
